server:
  port: 8082

spring:
  datasource:
    driver-class-nme: com.mysql.jdbc.Driver
    password: bode2001
    url: jdbc:mysql://localhost:3306/sms
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true