server:
  port: 8080

spring:
  datasource:
    driver-class-nme: com.mysql.jdbc.Driver
    password: bode2001
    url: jdbc:mysql://localhost:3306/bookstore
    username: root

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect