server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrationform
    username: root
    password: bode2001

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect