server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://myblogapp.cewanc9dqr24.us-east-1.rds.amazonaws.com:3306/myblogapp
    username: bodefaithful
    password: bode6192

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true