server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    username: root
    password: bode2001

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
